CREATE TABLE IF NOT EXISTS tai_currency_exchange_rate
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(8) NOT NULL,
	EXCHANGE_RATE DOUBLE NOT NULL,
	DATE_INSERT DATETIME NOT NULL,
	PRIMARY KEY (ID)
);
